# Site settings
title: Audrey Cigolotti.
email: cigolottiaudrey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! Welcome to my realm, where I showcase cherry-picked projects I work on over the years. 
  I would, of course, love to talk about them (or some others) in further detail during a conversation! 
  Don't hesitate to contact me. Cheers!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: audreycgltt
github_username:  audreycgltt
linkedin_username: audreycgltt
instagram_username: le_mastoq

# Build settings
markdown: kramdown
permalink: pretty
